<template>
  <CreateLayout>
    <div class="bg-indigo-400 py-1 fixed z-10 w-full">
      <div class="container flex justify-between items-center">
        <div class="flex items-center">
          <button class="mr-4" @click="$router.go(-1)">
            <i class="dripicons-cross text-white text-2xl"></i>
          </button>
          <span class="font-medium text-white mb-1">Создать</span>
        </div>
        <button @click="create">
          <i class="dripicons-checkmark text-white text-2xl"></i>
        </button>
      </div>
    </div>
    <div class="container pt-12 pb-3">
      <div v-for="field in fields" class="mb-1">
        <component
          v-if="field"
          :is="addTypeName(field.type.name)"
          :field="field"
          :fetch-record-item="fetchRecord[field.name]"
        ></component>
      </div>
      <time></time>
    </div>
  </CreateLayout>
</template>
<script>
import String from '../Fields/Form.vue';
import Date from '../Fields/Date.vue';
import Picklist from '../Fields/Dropdown.vue';
import AppTime from '../Fields/Time.vue';
import Boolean from '../Fields/Check.vue';
import Owner from '../Fields/GroupSelect.vue';
import Integer from '../Fields/Number.vue';
import Reference from '../Fields/Reference.vue';
export default {
  components: {
    String,
    Date,
    Picklist,
    AppTime,
    Boolean,
    Owner,
    Integer,
    Reference,
  },
  data() {
    return {
      fields: [],
      values: {},
      formData: {},
      dataItem: new FormData(),
      calendar: '',
      error: '',
      fetchRecord: {},
    };
  },
  created() {
    if (this.$route.params.action === 'edit')
      axios
        .post('api.php', {
          module: this.$route.params.name,
          record: this.$route.params.id,
          view_mode: 'web',
          _operation: 'fetchRecord',
        })
        .then(response => {
          this.fetchRecord = response.data.result.record;
        });

    if (this.$route.params.action === 'create' && this.$route.params.preset) {
      try {
        let presetFields = JSON.parse(this.$route.params.preset);

        for (const [field, value] of Object.entries(presetFields)) {
          this.fetchRecord[field] = value;
        }
      } catch (e) {
      }
    }

    axios
      .post('api.php', {
        module: this.$route.params.name,
        _operation: 'describe',
      })
      .then(response => {
        response.data.result.describe.fields.forEach(field => {
          if (field.editable || field.type.name === 'autogenerated') {
            this.fields.push(field);
          }
        });
      });
  },
  methods: {
    addTypeName(type) {
      switch (type) {
        case 'time':
          return 'app-time';
        case 'autogenerated':
            return '';
        case 'datetime':
        case 'phone':
        case 'email':
        case 'text':
        case 'url':
        case 'double':
        case 'currency':
        case 'multipicklist':
          return 'string';
        default:
          return type;
      }
    },
    create() {
      this.fields.forEach(field => {
        if (field.type.name != 'autogenerated') {
          field.fill(this.formData);
        } 
      });
      
      if (this.$route.params.action === 'edit') {
        this.dataItem.append('record', this.fetchRecord.id);
      }

      this.dataItem.append('module', this.$route.params.name);
      this.dataItem.append('_operation', 'saveRecord');
      this.dataItem.append('values', JSON.stringify(this.formData));

      axios.post('api.php', this.dataItem).then(({ data }) => {
        if (data.success) {
          this.$router.go(-1);
        } else {
          console.log(this.$notify);
          this.error = data.error.message;
          this.$notify({
            duration: 1000,
            group: 'warn',
            title: 'Ошибка!',
            text: data.error.message,
          });
        }
      });
    },
  },
};
</script>
<style lang="css">
input::placeholder {
  color: #838383 !important;
  font-weight: 600 !important;
}
</style>
